# yaml-language-server: $schema=./devcenter.schema.json

name: DevExP-dev
location: eastus2
catalogItemSyncEnableStatus: Enabled
microsoftHostedNetworkEnableStatus: Enabled
installAzureMonitorAgentEnableStatus: Enabled
identity:
  type: SystemAssigned
  roleAssignments:
    - "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
    - "b24988ac-6180-42a0-ab88-20f7382dd24c"
    - "eb960402-bf75-4cc3-8d68-35b34f960f72"
    - "18e40d4e-8d2e-438d-97e1-9528336e149c"
    - "45d50f46-0b78-4001-a660-4198cbe8cd05"
    - "331c37c6-af14-46d9-b9f4-e1909e1b95a0"
    - "cf7c76d2-98a3-4358-a134-615aa78bf44d"
    - "85a2d0d9-2eba-4c9c-b355-11c2cc0788ab"
    - "1ef6a3be-d0ac-425d-8c01-acb62866290b"

devBoxDefinitions:
  - name: backEndEngineer
    image: microsoftvisualstudio_visualstudioplustools_vs-2022-ent-general-win11-m365-gen2
    osStorageType: ssd_512gb
    imageVersion: latest
    sku: general_i_32c128gb512ssd_v2
    hibernateSupport: Disabled
    default: true

  - name: frontEndEngineer
    image: microsoftwindowsdesktop_windows-ent-cpc_win11-21h2-ent-cpc-m365
    osStorageType: ssd_256gb
    imageVersion: latest
    sku: general_i_16c64gb256ssd_v2
    hibernateSupport: Enabled
    default: true

catalogs:
  - name: customTasks
    type: gitHub
    uri: https://github.com/Evilazaro/DevExP-DevBox.git
    branch: main
    path: .configuration/devcenter/tasks
environmentTypes:
  - name: dev
  - name: staging
projects:
  - name: identityProvider
    description: identityProvider
    pools:
      - name: backEndEngineer
        devBoxDefinitionName: backEndEngineer
      - name: frontEndEngineer
        devBoxDefinitionName: frontEndEngineer
    environmentTypes:
      - name: dev
        deploymentTargetId: ""
    catalogs:
      - name: environments
        type: gitHub
        uri: https://github.com/Evilazaro/identityProvider.git
        branch: main
        path: .configuration/devcenter/environments/dev
    tags:
      environment: dev
      division: Platforms
      team: DevExP
      project: DevExP-DevBox
      costCenter: IT
      owner: Evilazaro
      resources: DevCenter

tags:
  environment: dev
  division: Platforms
  team: DevExP
  project: DevExP-DevBox
  costCenter: IT
  owner: Evilazaro
  resources: DevCenter
